version: '3.3'
services:
  node:
    image: node
    container_name: kepviselovalaszto-node
    command: >
      sh -c "npm i
             npm run dev"
    working_dir: /app
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongo
    
  mongo:
    image: mongo
    container_name: kepviselovalaszto-mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data/db:/data/db
